services:

  core:
    image: ghcr.io/moghtech/komodo-core:latest
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 9120:9120
    volumes:
      - /etc/komodo/backups:/backups
    environment:
      TZ: Etc/UTC
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: admin
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_HOST: localhost
      KOMODO_TITLE: josecgeo
      KOMODO_FIRST_SERVER: localhost:8120
      KOMODO_FIRST_SERVER_NAME: Local
      KOMODO_MONITORING_INTERVAL: "15-sec"
      KOMODO_RESOURCE_POLL_INTERVAL: "1-hr"
      KOMODO_JWT_TTL: "1-day"
      KOMODO_DISABLE_CONFIRM_DIALOG: true
      KOMODO_LOCAL_AUTH: true
      KOMODO_DISABLE_USER_REGISTRATION: false
      KOMODO_ENABLE_NEW_USERS: false
      KOMODO_DISABLE_NON_ADMIN_CREATE: false
      KOMODO_TRANSPARENT_MODE: false
      KOMODO_LOGGING_PRETTY: false
      KOMODO_PRETTY_STARTUP_CONFIG: false
      KOMODO_OIDC_ENABLED: false
      KOMODO_GITHUB_OAUTH_ENABLED: false
      KOMODO_GOOGLE_OAUTH_ENABLED: false
      KOMODO_WEBHOOK_SECRET: jmpdagdm
      KOMODO_JWT_SECRET: jmpdagdm
      KOMODO_PASSKEY: jmpdagdm
      PERIPHERY_PASSKEYS: jmpdagdm
      PERIPHERY_ROOT_DIRECTORY: /etc/komodo
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_SSL_ENABLED: true
      PERIPHERY_LOGGING_PRETTY: false
      PERIPHERY_PRETTY_STARTUP_CONFIG: false

  mongo:
    image: mongo
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - /etc/komodo/mongo/db:/data/db
      - /etc/komodo/mongo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
